include:
  - ./services/participants/consumer/docker-compose.yml
  - ./services/participants/provider/docker-compose.yml

services:

  dataspace-issuer:
    image: nginx:1.27.5
    container_name: dataspace-issuer
    ports:
      - "80:80"
    volumes:
      - ./services/issuer/nginx.conf:/etc/nginx/nginx.conf
      - ./services/issuer/did.json:/var/www/.well-known/did.json
    restart: always

